In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel('DatasetAutoRecovered.xlsx')
df.head()

SN                   Places                                        tags
0   1        Swyambunath Stupa  cultural, religious, wildlife, sightseeing
1   2     Pashupatinath Temple           religious, historical,sightseeing
2   3  Kathmandu Durbar Square           cultural, sightseeing, historical
3   4         Garden of Dreams                                 sightseeing
4   5         Boudhanath Stupa  cultural, religious, wildlife, sightseeing

In [3]:
df.shape

(104, 3)

In [4]:
df_final = df['Places']+' '+df['tags']

In [5]:
print(df_final)

0      Swyambunath Stupa cultural, religious, wildlif...
1      Pashupatinath Temple religious, historical,sig...
2      Kathmandu Durbar Square cultural, sightseeing,...
3                           Garden of Dreams sightseeing
4      Boudhanath Stupa cultural, religious, wildlife...
                             ...                        
99                                                   NaN
100                                                  NaN
101                                                  NaN
102                                                  NaN
103                                                  NaN
Length: 104, dtype: object


In [6]:
df_final = df_final.dropna()

In [7]:
print(df_final)

0     Swyambunath Stupa cultural, religious, wildlif...
1     Pashupatinath Temple religious, historical,sig...
2     Kathmandu Durbar Square cultural, sightseeing,...
3                          Garden of Dreams sightseeing
4     Boudhanath Stupa cultural, religious, wildlife...
                            ...                        
94                     Dreamland Eco Resort sightseeing
95               LOD - Lord Of The Drinks entertainment
96                         Dadagaun sightseeing ,hiking
97                        Kalu Pandey Danda sightseeing
98                  Central Zoo entertainment ,wildlife
Length: 99, dtype: object


In [8]:
df = df.dropna()

In [9]:
df

SN                    Places                                        tags
0    1         Swyambunath Stupa  cultural, religious, wildlife, sightseeing
1    2      Pashupatinath Temple           religious, historical,sightseeing
2    3   Kathmandu Durbar Square           cultural, sightseeing, historical
3    4          Garden of Dreams                                 sightseeing
4    5          Boudhanath Stupa  cultural, religious, wildlife, sightseeing
..  ..                       ...                                         ...
94  95      Dreamland Eco Resort                                 sightseeing
95  96  LOD - Lord Of The Drinks                               entertainment
96  97                  Dadagaun                         sightseeing ,hiking
97  98         Kalu Pandey Danda                                 sightseeing
98  99               Central Zoo                     entertainment ,wildlife

[99 rows x 3 columns]

In [10]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

count_matrix1 = cv.fit_transform(df_final).toarray()
count_matrix1

array([[0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 1]], dtype=int64)

In [11]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

count_matrix = cv.fit_transform(df['tags']).toarray()
count_matrix

array([[0, 0, 1, ..., 0, 1, 1],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 1, ..., 0, 1, 0],
       ...,
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 1]], dtype=int64)

In [12]:
count_matrix1.shape

(99, 174)

In [13]:
X_name = cv.get_feature_names()
X_name

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['adventerous',
 'art',
 'cultural',
 'entertainment',
 'hiking',
 'historic',
 'historical',
 'picnic',
 'religious',
 'sightseeeing',
 'sightseeing',
 'wildlife']

In [14]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(count_matrix)

similarity[0]

array([1.        , 0.57735027, 0.57735027, 0.5       , 1.        ,
       0.5       , 0.5       , 0.57735027, 0.8660254 , 0.5       ,
       0.5       , 0.35355339, 0.57735027, 0.5       , 0.35355339,
       0.57735027, 0.28867513, 0.5       , 0.        , 0.70710678,
       0.70710678, 0.5       , 0.70710678, 0.8660254 , 0.28867513,
       0.8660254 , 0.70710678, 0.5       , 0.70710678, 0.70710678,
       0.28867513, 0.70710678, 0.        , 0.        , 0.        ,
       0.70710678, 0.5       , 0.57735027, 0.35355339, 0.28867513,
       0.        , 0.28867513, 0.35355339, 0.35355339, 0.5       ,
       0.75      , 0.28867513, 0.25      , 0.        , 0.35355339,
       0.        , 0.        , 0.        , 0.35355339, 0.        ,
       0.28867513, 0.35355339, 0.35355339, 0.70710678, 0.70710678,
       0.70710678, 0.35355339, 0.28867513, 0.35355339, 0.57735027,
       0.        , 0.25      , 0.        , 0.28867513, 0.70710678,
       0.70710678, 0.35355339, 0.70710678, 0.35355339, 0.35355

In [15]:
from sklearn.metrics.pairwise import cosine_similarity
similarity1 = cosine_similarity(count_matrix1)

In [16]:
similarity[0]

array([1.        , 0.57735027, 0.57735027, 0.5       , 1.        ,
       0.5       , 0.5       , 0.57735027, 0.8660254 , 0.5       ,
       0.5       , 0.35355339, 0.57735027, 0.5       , 0.35355339,
       0.57735027, 0.28867513, 0.5       , 0.        , 0.70710678,
       0.70710678, 0.5       , 0.70710678, 0.8660254 , 0.28867513,
       0.8660254 , 0.70710678, 0.5       , 0.70710678, 0.70710678,
       0.28867513, 0.70710678, 0.        , 0.        , 0.        ,
       0.70710678, 0.5       , 0.57735027, 0.35355339, 0.28867513,
       0.        , 0.28867513, 0.35355339, 0.35355339, 0.5       ,
       0.75      , 0.28867513, 0.25      , 0.        , 0.35355339,
       0.        , 0.        , 0.        , 0.35355339, 0.        ,
       0.28867513, 0.35355339, 0.35355339, 0.70710678, 0.70710678,
       0.70710678, 0.35355339, 0.28867513, 0.35355339, 0.57735027,
       0.        , 0.25      , 0.        , 0.28867513, 0.70710678,
       0.70710678, 0.35355339, 0.70710678, 0.35355339, 0.35355

In [17]:
similarity[0].shape

(99,)

In [18]:
sorted(similarity[0],reverse=True)

[1.0,
 1.0,
 0.8660254037844388,
 0.8660254037844388,
 0.8660254037844388,
 0.75,
 0.7071067811865475,
 0.7071067811865475,
 0.7071067811865475,
 0.7071067811865475,
 0.7071067811865475,
 0.7071067811865475,
 0.7071067811865475,
 0.7071067811865475,
 0.7071067811865475,
 0.7071067811865475,
 0.7071067811865475,
 0.7071067811865475,
 0.7071067811865475,
 0.7071067811865475,
 0.7071067811865475,
 0.7071067811865475,
 0.5773502691896258,
 0.5773502691896258,
 0.5773502691896258,
 0.5773502691896258,
 0.5773502691896258,
 0.5773502691896258,
 0.5773502691896258,
 0.5,
 0.5,
 0.5,
 0.5,
 0.5,
 0.5,
 0.5,
 0.5,
 0.5,
 0.5,
 0.5,
 0.5,
 0.5,
 0.5,
 0.5,
 0.5,
 0.5,
 0.35355339059327373,
 0.35355339059327373,
 0.35355339059327373,
 0.35355339059327373,
 0.35355339059327373,
 0.35355339059327373,
 0.35355339059327373,
 0.35355339059327373,
 0.35355339059327373,
 0.35355339059327373,
 0.35355339059327373,
 0.35355339059327373,
 0.35355339059327373,
 0.35355339059327373,
 0.35355339059327373,
 0.

In [19]:
# Capturing the index position 
list(enumerate(similarity[0]))

[(0, 1.0),
 (1, 0.5773502691896258),
 (2, 0.5773502691896258),
 (3, 0.5),
 (4, 1.0),
 (5, 0.5),
 (6, 0.5),
 (7, 0.5773502691896258),
 (8, 0.8660254037844388),
 (9, 0.5),
 (10, 0.5),
 (11, 0.35355339059327373),
 (12, 0.5773502691896258),
 (13, 0.5),
 (14, 0.35355339059327373),
 (15, 0.5773502691896258),
 (16, 0.2886751345948129),
 (17, 0.5),
 (18, 0.0),
 (19, 0.7071067811865475),
 (20, 0.7071067811865475),
 (21, 0.5),
 (22, 0.7071067811865475),
 (23, 0.8660254037844388),
 (24, 0.2886751345948129),
 (25, 0.8660254037844388),
 (26, 0.7071067811865475),
 (27, 0.5),
 (28, 0.7071067811865475),
 (29, 0.7071067811865475),
 (30, 0.2886751345948129),
 (31, 0.7071067811865475),
 (32, 0.0),
 (33, 0.0),
 (34, 0.0),
 (35, 0.7071067811865475),
 (36, 0.5),
 (37, 0.5773502691896258),
 (38, 0.35355339059327373),
 (39, 0.2886751345948129),
 (40, 0.0),
 (41, 0.2886751345948129),
 (42, 0.35355339059327373),
 (43, 0.35355339059327373),
 (44, 0.5),
 (45, 0.75),
 (46, 0.2886751345948129),
 (47, 0.25),
 (48, 0

In [20]:
# Getting the first five recommendations from similarity

sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]

[(4, 1.0),
 (8, 0.8660254037844388),
 (23, 0.8660254037844388),
 (25, 0.8660254037844388),
 (45, 0.75)]

In [21]:
def recommend(places):
    places_index = df[df['Places'] == places].index[0]
    distances = similarity[places_index]
    places_list = sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
    
    for i in places_list:
        print(df.iloc[i[0]].Places)

In [22]:
def recommend1(places):
    places_index = df[df['Places'] == places].index[0]
    distances = similarity1[places_index]
    places_list = sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
    
    for i in places_list:
        print(df.iloc[i[0]].Places)

In [23]:
recommend('Swyambunath Stupa')

Boudhanath Stupa
Budhanilkantha Temple
Jagannath Temple
Vajrayogini Temple
Namo Buddha


In [24]:
recommend1('Swyambunath Stupa')

Boudhanath Stupa
Budhanilkantha Temple
Jagannath Temple
Vajrayogini Temple
Chabahil Stupa


In [25]:
df.iloc[4].Places

'Boudhanath Stupa'

In [26]:
recommend('Garden of Dreams')

Kumari Bahal
Kopan Monastery
Asan Tole
White Monastery
Taudaha Lake


In [27]:
recommend1('Garden of Dreams')

House of Palettes
National Museum of Nepal
Thamel
Pharping
Kumari Bahal


In [28]:
import pickle

In [29]:
pickle.dump(df,open('places.pickle','wb'))

In [30]:
pickle.dump(df.to_dict(),open('places_dict.pickle','wb'))

In [31]:
df['Places'].values

array(['Swyambunath Stupa', 'Pashupatinath Temple',
       'Kathmandu Durbar Square', 'Garden of Dreams', 'Boudhanath Stupa',
       'Kumari Bahal', 'Kopan Monastery', 'Narayanhiti Palace',
       'Budhanilkantha Temple', 'Asan Tole', 'White Monastery',
       'Dharahara', 'Hanuman Dhoka', 'Taudaha Lake',
       'Siddhartha Art Gallery', 'Pulchoki', 'The Last Resort', 'Thamel',
       'Bhundole', 'Dakshinkali Temple', 'Patan', 'Indra Chowk',
       'Kala Bhairav', 'Jagannath Temple', 'National Museum of Nepal',
       'Vajrayogini Temple', 'Taleju Temple',
       'National Botanical Gardens', 'Akash Bhairav Temple',
       'Seto Machindranath Temple', 'Tribhuvan Museum',
       'Shiva-Parvati Temple', 'Kaiser Library', 'Stone Inscription',
       'Casino Royale', 'Annapurna Temple', 'Chhauni Museum',
       'Chabahil Stupa', 'Freak Street', 'chandragiri',
       'Kathmandu Fun Park', 'Nagarkot', 'Dhulikhel', 'Chobhar Danda',
       'Pharping', 'Namo Buddha', 'JarsingPauwa', 'Lakuri Bha

In [32]:
df.to_dict()

{'SN': {0: 1,
  1: 2,
  2: 3,
  3: 4,
  4: 5,
  5: 6,
  6: 7,
  7: 8,
  8: 9,
  9: 10,
  10: 11,
  11: 12,
  12: 13,
  13: 14,
  14: 15,
  15: 16,
  16: 17,
  17: 18,
  18: 19,
  19: 20,
  20: 21,
  21: 22,
  22: 23,
  23: 24,
  24: 25,
  25: 26,
  26: 27,
  27: 28,
  28: 29,
  29: 30,
  30: 31,
  31: 32,
  32: 33,
  33: 34,
  34: 35,
  35: 36,
  36: 37,
  37: 38,
  38: 39,
  39: 40,
  40: 41,
  41: 42,
  42: 43,
  43: 44,
  44: 45,
  45: 46,
  46: 47,
  47: 48,
  48: 49,
  49: 50,
  50: 21,
  51: 52,
  52: 53,
  53: 54,
  54: 55,
  55: 56,
  56: 57,
  57: 58,
  58: 59,
  59: 60,
  60: 61,
  61: 62,
  62: 63,
  63: 64,
  64: 65,
  65: 66,
  66: 67,
  67: 68,
  68: 69,
  69: 70,
  70: 71,
  71: 72,
  72: 73,
  73: 74,
  74: 75,
  75: 76,
  76: 77,
  77: 78,
  78: 79,
  79: 80,
  80: 81,
  81: 82,
  82: 83,
  83: 84,
  84: 85,
  85: 86,
  86: 87,
  87: 88,
  88: 89,
  89: 90,
  90: 91,
  91: 92,
  92: 93,
  93: 94,
  94: 95,
  95: 96,
  96: 97,
  97: 98,
  98: 99},
 'Places': {0: 'Swyamb

In [33]:
pickle.dump(similarity,open('similarity.pkl', 'wb'))

In [34]:
from sklearn.neighbors import NearestNeighbors
model_knn = NearestNeighbors(metric='cosine', algorithm='brute', n_neighbors=20, n_jobs=-1)

In [35]:
from scipy.sparse import csr_matrix

places_sparse = csr_matrix(count_matrix)

In [36]:
places_sparse

<99x12 sparse matrix of type '<class 'numpy.int64'>'
	with 202 stored elements in Compressed Sparse Row format>

In [37]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()

transformed = tfidf.fit_transform(df_final)

In [38]:
transformed

<99x174 sparse matrix of type '<class 'numpy.float64'>'
	with 419 stored elements in Compressed Sparse Row format>

In [39]:
print(transformed)

  (0, 143)	0.14694227090995546
  (0, 171)	0.44883345924934154
  (0, 133)	0.3131645868727926
  (0, 41)	0.3131645868727926
  (0, 149)	0.4965561727449693
  (0, 154)	0.5781386903196754
  (1, 68)	0.41712645455932856
  (1, 159)	0.3830912701672577
  (1, 123)	0.7072315788290724
  (1, 143)	0.17975308691918618
  (1, 133)	0.3830912701672577
  (2, 146)	0.47385490661904583
  (2, 53)	0.5344338472678778
  (2, 83)	0.5003175571250542
  (2, 68)	0.34357019587832033
  (2, 143)	0.14805535014028612
  (2, 41)	0.3155367905631574
  (3, 51)	0.6056363018185963
  (3, 114)	0.4926606643613469
  (3, 59)	0.6056363018185963
  (3, 143)	0.15393118472234354
  (4, 23)	0.5781386903196754
  (4, 143)	0.14694227090995546
  (4, 171)	0.44883345924934154
  (4, 133)	0.3131645868727926
  :	:
  (93, 24)	0.36602779643298183
  (93, 5)	0.3143767486215767
  (93, 105)	0.297748825200715
  (93, 143)	0.09303123372402122
  (94, 54)	0.5865811530375713
  (94, 50)	0.5865811530375713
  (94, 134)	0.5381615527287449
  (94, 143)	0.1490880443456587

In [40]:
type(tfidf)

sklearn.feature_extraction.text.TfidfVectorizer

In [41]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(transformed)

In [42]:
print(similarity)

[[1.         0.14638395 0.12057054 ... 0.03175714 0.02286783 0.20285476]
 [0.14638395 1.         0.16992562 ... 0.0388482  0.027974   0.        ]
 [0.12057054 0.16992562 1.         ... 0.0319977  0.02304105 0.        ]
 ...
 [0.03175714 0.0388482  0.0319977  ... 1.         0.03363356 0.        ]
 [0.02286783 0.027974   0.02304105 ... 0.03363356 1.         0.        ]
 [0.20285476 0.         0.         ... 0.         0.         1.        ]]


In [43]:
print(similarity.shape)

(99, 99)


In [44]:
# Getting the neame of place from user

place_name = input('Enter your place you would love to visit :')

Enter your place you would love to visit :Anantalingeshwar Mahadev Temple


In [45]:
type(place_name)

str

In [46]:
#  Creating the list of all the places

places_list = df['Places'].tolist()
print(places_list)

['Swyambunath Stupa', 'Pashupatinath Temple', 'Kathmandu Durbar Square', 'Garden of Dreams', 'Boudhanath Stupa', 'Kumari Bahal', 'Kopan Monastery', 'Narayanhiti Palace', 'Budhanilkantha Temple', 'Asan Tole', 'White Monastery', 'Dharahara', 'Hanuman Dhoka', 'Taudaha Lake', 'Siddhartha Art Gallery', 'Pulchoki', 'The Last Resort', 'Thamel', 'Bhundole', 'Dakshinkali Temple', 'Patan', 'Indra Chowk', 'Kala Bhairav', 'Jagannath Temple', 'National Museum of Nepal', 'Vajrayogini Temple', 'Taleju Temple', 'National Botanical Gardens', 'Akash Bhairav Temple', 'Seto Machindranath Temple', 'Tribhuvan Museum', 'Shiva-Parvati Temple', 'Kaiser Library', 'Stone Inscription', 'Casino Royale', 'Annapurna Temple', 'Chhauni Museum', 'Chabahil Stupa', 'Freak Street', 'chandragiri', 'Kathmandu Fun Park', 'Nagarkot', 'Dhulikhel', 'Chobhar Danda', 'Pharping', 'Namo Buddha', 'JarsingPauwa', 'Lakuri Bhanjyang', 'Jump KTM', 'Art in Paradise Nepal', 'Whoopee Land', 'Astrek Park', 'Kathmandu Sports and Climbing Cen

In [47]:
type(places_list)

list

In [48]:
# Finding the closest match for the place

import difflib
from difflib import get_close_matches  

In [49]:
close_match = difflib.get_close_matches(place_name, places_list)
print(close_match)

['Anantalingeshwar Mahadev Temple', 'Doleshwar Mahadev Temple', 'Subarneshwar Mahadev Temple']
